# Generated by Django 6.0.8 on 2026-08-10 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_remove_post_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='postimage',
            name='image_alt',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
