# Generated by Django 6.0.8 on 2026-08-10 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_postimage_image_alt'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postimage',
            name='image_alt',
        ),
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
    ]
