# Generated by Django 6.0.8 on 2026-08-10 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_remove_post_image_remove_post_image_alt'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(blank=True, default='', upload_to='images/'),
        ),
        migrations.AddField(
            model_name='post',
            name='image_alt',
            field=models.CharField(max_length=350, null=True),
        ),
    ]
