# Generated by Django 6.0.8 on 2026-08-10 18:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_postimage_image_alt'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postimage',
            name='image_alt',
            field=models.CharField(default='img', max_length=350),
        ),
    ]
