# Generated by Django 6.0.8 on 2026-08-10 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_alter_postimage_image_alt'),
    ]

    operations = [
        migrations.RenameField(
            model_name='postimage',
            old_name='image_alt',
            new_name='image_alt_text',
        ),
    ]
