# Generated by Django 6.0.8 on 2026-08-26 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0014_post_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
    ]
