# Generated by Django 6.0.8 on 2026-09-01 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_delete_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='image',
            new_name='images',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='image',
            new_name='images',
        ),
    ]
