# Generated by Django 6.0.8 on 2026-09-01 16:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_post_images'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='images',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='postimage',
            old_name='images',
            new_name='image',
        ),
    ]
